pointcloud_transform_node:
  ros__parameters:
    input_topic: /zed/zed_node/point_cloud/cloud_registered
    output_topic: /lr/point_cloud/cloud_in_map
    target_frame: map
    transform_timeout_sec: 0.5
